/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollaboratorStrip: typeof import('./components/CollaboratorStrip.vue')['default']
    CollapsiblePanel: typeof import('./components/CollapsiblePanel.vue')['default']
    EChartPanel: typeof import('./components/EChartPanel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FolderTreePanel: typeof import('./components/FolderTreePanel.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    NoteSearchSelect: typeof import('./components/NoteSearchSelect.vue')['default']
    NotificationCenter: typeof import('./components/NotificationCenter.vue')['default']
    PageHero: typeof import('./components/PageHero.vue')['default']
    QuickSwitcher: typeof import('./components/QuickSwitcher.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCloudPanel: typeof import('./components/TagCloudPanel.vue')['default']
  }
}
